### ISSUE TITLE
add a gif on editing a photo using the starter project

### ISSUE THREAD

**Issue by yan7109** [Polarrco/PolarrPhotoEditorAndroidSDK#1]
include import
a couple edits
zoom
and export

**Comment by c01-in** [comment]
![ppe_demo](https://user-images.githubusercontent.com/5923363/28439929-bcdd097a-6dd6-11e7-8456-beef54bfaac8.gif)

**Comment by c01-in** [comment]
2cf9f500cc6d02c109670cf404be0798a229ba42
